export const cometAbi = [
  {
    name: "name",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    name: "version",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "constructor",
    inputs: [{ name: "_name32", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "MAX_ASSETS",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowBySig",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "manager", type: "address", internalType: "address" },
      { name: "asset", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "nonce", type: "uint256", internalType: "uint256" },
      { name: "expiry", type: "uint256", internalType: "uint256" },
      { name: "v", type: "uint8", internalType: "uint8" },
      { name: "r", type: "bytes32", internalType: "bytes32" },
      { name: "s", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getUtilization",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getReserves",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalBorrow",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "utilization",
        type: "uint256",
      },
    ],
    name: "getSupplyRate",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "utilization",
        type: "uint256",
      },
    ],
    name: "getBorrowRate",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "priceFeed",
        type: "address",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getCollateralReserves",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "borrowBalanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "allowanceAll",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "manager", type: "address" },
      { internalType: "bool", name: "approved", type: "bool" },
      { internalType: "uint256", name: "nonce", type: "uint256" },
      { internalType: "uint256", name: "expiry", type: "uint256" },
      { internalType: "uint8", name: "v", type: "uint8" },
      { internalType: "bytes32", name: "r", type: "bytes32" },
      { internalType: "bytes32", name: "s", type: "bytes32" },
    ],
    name: "allowAllBySig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "asset", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "approveAllTokens",
    inputs: [
      { name: "spender bulker", type: "address", internalType: "address" },
      { name: "baseTokenAmount", type: "uint256", internalType: "uint256" },
      { name: "amounts", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "assetFeesController",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "assetFeesDAO",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "baseAccrualScale",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "baseBorrowMin",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "baseIndexScale",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "baseMinForRewards",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "baseScale",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "baseToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "baseTokenPriceFeed",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "baseTrackingAccrued",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "baseTrackingBorrowSpeed",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "baseTrackingSupplySpeed",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "borrowKink",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "borrowPerSecondInterestRateBase",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "borrowPerSecondInterestRateSlopeHigh",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "borrowPerSecondInterestRateSlopeLow",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "collateralAssetIndex",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "collateralAssets",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "collateralToken", type: "address", internalType: "address" },
      { name: "priceFeed", type: "address", internalType: "address" },
      { name: "supplyCap", type: "uint128", internalType: "uint128" },
      {
        name: "borrowCollateralFactor",
        type: "uint64",
        internalType: "uint64",
      },
      {
        name: "liquidateCollateralFactor",
        type: "uint64",
        internalType: "uint64",
      },
      { name: "liquidationFactor", type: "uint64", internalType: "uint64" },
      { name: "scale", type: "uint64", internalType: "uint64" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "collateralBalanceOf",
    inputs: [
      { name: "account", type: "address", internalType: "address" },
      { name: "asset", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "configController",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "extension",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "factorScale",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "factory",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getConfiguration",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct ICometExtension.Configuration",
        components: [
          {
            name: "configController",
            type: "address",
            internalType: "address",
          },
          { name: "baseToken", type: "address", internalType: "address" },
          {
            name: "baseTokenPriceFeed",
            type: "address",
            internalType: "address",
          },
          {
            name: "extensionDelegate",
            type: "address",
            internalType: "address",
          },
          { name: "supplyKink", type: "uint64", internalType: "uint64" },
          {
            name: "supplyPerYearInterestRateSlopeLow",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "supplyPerYearInterestRateSlopeHigh",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "supplyPerYearInterestRateBase",
            type: "uint64",
            internalType: "uint64",
          },
          { name: "borrowKink", type: "uint64", internalType: "uint64" },
          {
            name: "borrowPerYearInterestRateSlopeLow",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "borrowPerYearInterestRateSlopeHigh",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "borrowPerYearInterestRateBase",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "storeFrontPriceFactor",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "trackingIndexScale",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "baseTrackingSupplySpeed",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "baseTrackingBorrowSpeed",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "baseMinForRewards",
            type: "uint104",
            internalType: "uint104",
          },
          { name: "baseBorrowMin", type: "uint104", internalType: "uint104" },
          { name: "targetPercent", type: "uint64", internalType: "uint64" },
          { name: "seedReserves", type: "uint104", internalType: "uint104" },
          { name: "unlockTimestamp", type: "uint64", internalType: "uint64" },
          {
            name: "assetConfigs",
            type: "tuple[]",
            internalType: "struct CometStorage.CollateralAsset[]",
            components: [
              {
                name: "collateralToken",
                type: "address",
                internalType: "address",
              },
              { name: "priceFeed", type: "address", internalType: "address" },
              { name: "supplyCap", type: "uint128", internalType: "uint128" },
              {
                name: "borrowCollateralFactor",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "liquidateCollateralFactor",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "liquidationFactor",
                type: "uint64",
                internalType: "uint64",
              },
              { name: "scale", type: "uint64", internalType: "uint64" },
            ],
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasPermission",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "manager", type: "address", internalType: "address" },
      { name: "asset", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxAssets",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "numAssets",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sandboxController",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "seedReserves",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "storeFrontPriceFactor",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "supplyKink",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "supplyPerSecondInterestRateBase",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "supplyPerSecondInterestRateSlopeHigh",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "supplyPerSecondInterestRateSlopeLow",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "targetPercent",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalsBasic",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct CometStorage.TotalsBasic",
        components: [
          { name: "baseSupplyIndex", type: "uint64", internalType: "uint64" },
          { name: "baseBorrowIndex", type: "uint64", internalType: "uint64" },
          {
            name: "trackingSupplyIndex",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "trackingBorrowIndex",
            type: "uint64",
            internalType: "uint64",
          },
          { name: "totalSupplyBase", type: "uint104", internalType: "uint104" },
          { name: "totalBorrowBase", type: "uint104", internalType: "uint104" },
          { name: "lastAccrualTime", type: "uint40", internalType: "uint40" },
          { name: "pauseFlags", type: "uint8", internalType: "uint8" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalsCollateral",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "trackingIndexScale",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "unlockTimestamp",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "userBasic",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [
      { name: "principal", type: "int104", internalType: "int104" },
      { name: "baseTrackingIndex", type: "uint64", internalType: "uint64" },
      { name: "baseTrackingAccrued", type: "uint64", internalType: "uint64" },
      { name: "assetsIn", type: "uint24", internalType: "uint24" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "userCollateral",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "userNonce",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AbsorbCollateral",
    inputs: [
      {
        name: "absorber",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "borrower",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "collateralAbsorbed",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "usdValue",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AbsorbDebt",
    inputs: [
      {
        name: "absorber",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "borrower",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "basePaidOut",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "usdValue",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "spender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BuyCollateral",
    inputs: [
      {
        name: "buyer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "baseAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "collateralAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ControllerFeeDisabled",
    inputs: [
      { name: "disabled", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeesExtracted",
    inputs: [
      {
        name: "comet",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amoint",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      { name: "to", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PauseAction",
    inputs: [
      {
        name: "supplyPaused",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "transferPaused",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "withdrawPaused",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "absorbPaused",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      { name: "buyPaused", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Supply",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "dst", type: "address", indexed: true, internalType: "address" },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SupplyCollateral",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "dst", type: "address", indexed: true, internalType: "address" },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TransferCollateral",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Withdraw",
    inputs: [
      { name: "src", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WithdrawCollateral",
    inputs: [
      { name: "src", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadyInitialized", inputs: [] },
  { type: "error", name: "AmountTooSmall", inputs: [] },
  { type: "error", name: "BadAsset", inputs: [] },
  { type: "error", name: "BadDecimals", inputs: [] },
  { type: "error", name: "BadNonce", inputs: [] },
  { type: "error", name: "BadPrice", inputs: [] },
  { type: "error", name: "BadSignatory", inputs: [] },
  { type: "error", name: "BorrowTooSmall", inputs: [] },
  { type: "error", name: "IncorrectInitialization", inputs: [] },
  {
    type: "error",
    name: "InsufficientAllowance",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "owner", type: "address", internalType: "address" },
      { name: "manager", type: "address", internalType: "address" },
    ],
  },
  { type: "error", name: "InsufficientReserves", inputs: [] },
  { type: "error", name: "InvalidInt104", inputs: [] },
  { type: "error", name: "InvalidInt256", inputs: [] },
  { type: "error", name: "InvalidLength", inputs: [] },
  { type: "error", name: "InvalidUInt104", inputs: [] },
  { type: "error", name: "InvalidUInt128", inputs: [] },
  { type: "error", name: "InvalidUInt64", inputs: [] },
  { type: "error", name: "InvalidValueS", inputs: [] },
  { type: "error", name: "InvalidValueV", inputs: [] },
  { type: "error", name: "NegativeNumber", inputs: [] },
  { type: "error", name: "NoSelfTransfer", inputs: [] },
  { type: "error", name: "NotCollateralized", inputs: [] },
  { type: "error", name: "NotLiquidatable", inputs: [] },
  { type: "error", name: "Paused", inputs: [] },
  { type: "error", name: "ReentrantCallBlocked", inputs: [] },
  { type: "error", name: "SignatureExpired", inputs: [] },
  { type: "error", name: "SupplyCapExceeded", inputs: [] },
  { type: "error", name: "TimestampTooLarge", inputs: [] },
  { type: "error", name: "TooManyAssets", inputs: [] },
  { type: "error", name: "TooMuchSlippage", inputs: [] },
  { type: "error", name: "Unauthorized", inputs: [] },
  {
    type: "error",
    name: "WrongToken",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
] as const;
